### ISSUE TITLE
App crashes on welcome screen after background and foreground

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#925] opened 2019-04-23 12:28 UTC
Build: 1.5.0 (2999)
Device: iPhone 7
iOS: 12.1

Steps to reproduce:
1. Clean install and launch Lockbox
2. Background by tapping on the home button
3. Foreground the app

Actual results: 
-  Lockbox will crash. 

Notes:
- Might be duplicate of https://github.com/mozilla-lockbox/lockbox-ios/issues/923
- Not reproducible on 11.x

[Firefox Lockbox-2019-04-23-152010.ips.beta.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/3107461/Firefox.Lockbox-2019-04-23-152010.ips.beta.zip)

**Comment by sashei** [comment] 2019-04-24 01:33
@SimonBasca I'm not sure what the `ips.beta` fileformat denotes, mind elaborating on how to access logs or video (I'm assuming?)

**Comment by SimonBasca** [comment] 2019-04-24 07:36
Hey @sashei. That's the crash log I extracted via syncing with iTunes on actual device. For some recons I can get the crash via Xcode. I usually just open it and select open with Xcode, although the crash log needs symbolicating. 

I crashed again on simulator and got that crash log which more readable.

**Comment by sashei** [comment] 2019-04-24 20:26
Thank you for that updated log file @SimonBasca !! Reading through those, I think this is a duplicate of #923.

**Closed by sashei** 2019-04-24 20:26 UTC
Labels: bug, on-deck
