### ISSUE TITLE
Authorization code is requested a second time after inputting the credentials

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#394] opened 2018-05-18 13:01 UTC
Build 1.0 (1128)
Device: iPhone 7 iOS 11.4b5

Steps to reproduce: 
1. Go to Sign In  screen
2. Log in with invalid credentials until "Authorize this sign-in" message is shown
3. Enter the authorization code received by email
4. Enter the correct credentials

Results:
- The "Authorize this sign-in" message is shown a second time and a new email is received. After inputting the second authorization code, the user is signed in to FxA.

**Comment by devinreams** [comment] 2018-05-18 16:13
Quick review:

- Never seen this before (was an FxA experiment I believe?)
- Could be due to delay on FxA side

@SimonBasca are you able to reproduce this again and show a video of what does/not happen?

**Comment by SimonBasca** [comment] 2018-05-21 11:45
Here is a video of the issue: https://www.youtube.com/watch?v=tbu-Fyg1HbE&pbjreload=10

The video starts after step 2), when the authorization code is requested after trying to log in with invalid credentials several times.

**Comment by rfk** [comment] 2018-05-22 23:16
This is a known issue on the FxA side, ref https://github.com/mozilla/fxa-auth-server/issues/1998

Basically, the authentication code is single-use, and it's consumed *before* we're able to check whether or not the password is correct.  So the user winds up in a flow like:

* User attempts to login with incorrect password.
* FxA notices that they're rate-limited, prompts to enter authorization code.
* User enters authorization code.
* FxA checks the password, finds it is incorrect, shows an "incorrect password" error.
* User enters correct password and tries to login again.
* FxA notices that they're rate-limited, prompts to enter authorization code.
* User enters authorization code.
* FxA checks the password, finds it is correct, allows the login to proceed.

The above-linked issue is to allow the same code to be used more than once, which is conceptually pretty straightforward, but just hasn't been prioritized.

**Comment by devinreams** [comment] 2018-05-23 13:57
>This is a known issue on the FxA side

Thank you, @rfk.

I added the "blocked" label here for easy tracking on our side and I'll "subscribe" to that issue to watch for movement...

**Comment by rfk** [comment] 2018-05-23 20:53
I'm interpreting the "P3" label here as meaning this is not a high-severity issue from your side, but please correct me if you'd like us to raise the priority of this.

**Comment by sandysage** [comment] 2019-04-24 21:23
Not an issue for lockbox. Closing

**Closed by sandysage** 2019-04-24 21:23 UTC
Labels: P3, bug
