### ISSUE TITLE
The app is incorrectly uninstalled after tapping "Lock Now"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#393] opened 2018-05-18 11:07 UTC
Build: 1.0 (1128)
Device: iPhone 7 iOS 11.4

Steps to reproduce:
1. Launch Lockbox
2. Log in to FxA
3. From Settings, tap "Lock Now"
4. Delete the app
5. Re-install the app

Results:
- After re-installing the app, the "Get started" button is not displayed. After deleting and re-installing a second time, the "Get started" button will be displayed.

Video link: https://www.youtube.com/watch?v=dCrMMuKsIlw&pbjreload=10

Notes: Could be related or duplicate of #366

**Comment by devinreams** [comment] 2018-05-18 16:07
Duplicate of #374

**Closed by devinreams** 2018-05-18 16:07 UTC
Labels: bug, closed-duplicate
