### ISSUE TITLE
"lookup" context menu crashes the app

### ISSUE THREAD

**Issue by pauljt** [mozilla-lockbox/lockbox-ios#369] opened 2018-05-16 07:09 UTC
STR:
 1. have no account connected
 2. clicked "get started" top open Fxa login
3. long press on some text in the page to bring up context menu
4. Choose "lookup"

App always crashes.

**Comment by devinreams** [comment] 2018-05-18 13:46
@pauljt I tried "Lookup" in both the FxA webview (Get Started/FxA sign in) and the settings webview (Send Feedback) and it didn't crash. It pulled up an overlay with the search results.

![img_2899](https://user-images.githubusercontent.com/49511/40238145-9905f0ee-5a6f-11e8-8721-1165393a40fb.png)


It doesn't look pretty but also doesn't crash here on iPhone X, iOS 11. What kind of device did you crash with?

**Comment by devinreams** [comment] 2018-06-08 19:37
Closing as I cannot reproduce "Lookup" crashing in any web views (FAQ, FxA).

**Closed by devinreams** 2018-06-08 19:37 UTC
Labels: bug
