### ISSUE TITLE
Lockbox can be unlocked without using biometrics

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#715] opened 2018-09-13 12:39 UTC
Build: 15e1604
Device: iPhone 7
iOS: 12b6

Preconditions:
- Clean install
- Log in to Lockbox
- Enable Autofill for Lockbox from iOS settings
- Autolock timer set to 1 minute

Steps to reproduce:
1.  Open Lockbox
2. From Settings tap on "Lock Now" 
3. Background Lockbox
4. Open iOS Settings -> Autofill Passwords
5. Uncheck Autofill Passwords for Lockbox
6. Check  Autofill Passwords for Lockbox
7. Forground Lockbox

Actual results:
- Lockbox will be unlocked without using biometrics.

Video here: https://www.youtube.com/watch?v=bhxiB6g5rc4

Note: 
- This issue is not always reproducible. Sometimes repeating steps 3) to 7) is necessary.

**Comment by devinreams** [comment] 2018-09-13 14:00
Duplicate of #699 

Thanks @SimonBasca, I believe @sashei fixed the issue causing this and will re-test and merge shortly.

**Closed by devinreams** 2018-09-13 14:00 UTC
Labels: bug
