### ISSUE TITLE
Lock Now with Face ID immediately unlocks

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockbox/lockbox-ios#384] opened 2018-05-17 20:14 UTC
I am not sure if this is a bug but the user experience is odd.

Go into settings and select Lock Now.

If you are facing your phone, Face ID will immediately activate, see your face and unlock your device. As if nothing happened - you are still in the settings.

I think maybe for this case it is better to show the app lock screen but instead of immediately trying to unlock, show a 'Use Face ID' or 'Unlock' button that lets you start the authentication manually.

**Comment by devinreams** [comment] 2018-05-17 21:20
Agreed, @sashei and I discussed this and thought a simple candidate that might make this straight forward is to just have the Face/Finger icon (button) appear on the "Welcome" screen and not immediately prompt if the user manually locked: #343

**Comment by changecourse** [comment] 2018-05-18 01:49
Sounds good.

**Comment by devinreams** [comment] 2018-05-18 13:09
Duplicate of #343

**Closed by devinreams** 2018-05-18 13:09 UTC
Labels: bug, closed-duplicate
