### ISSUE TITLE
Credential list not available when trying to autofill credentials via Lockbox

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#704] opened 2018-09-12 14:21 UTC
Build: 15e1604f4e05a
Device: iPhone 7
iOS: 12b6

Pre - conditions:
- Clean install
- Log in to Lockbox 
- Enable Autofill for Lockbox from iOS settings

Steps to reproduce:
1.  In Firefox for iOS go to facebook.com
2. Tap on the username field
3. Tap on the Autofill icon 
4. From the Autofill list, tap on Lockbox

Actual results:
- Lockbox app is opened and a prompt is displayed (Credential
 list not available yet. Please check back later)

![screen shot 2018-09-12 at 5 19 15 pm](https://user-images.githubusercontent.com/32130829/45431302-09388b00-b6b0-11e8-9ee8-a3ceb7a2f597.png)

**Comment by devinreams** [comment] 2018-09-12 14:33
Ah yes, this work is wrapping up at #682. Right now that semi-official looking alert/prompt is just a placeholder from us. Thanks for catching this @SimonBasca.

**Comment by devinreams** [comment] 2018-09-12 14:46
Duplicate of #616

**Closed by devinreams** 2018-09-12 14:46 UTC
