### ISSUE TITLE
Logins screen flickers after searching for a login, backgrounding and restoring the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#377] opened 2018-05-17 15:02 UTC
Phone 7 (11.4b5)
Build 1.0 (1128)

Preconditions:
- Set up touch ID
- Set Auto Lock - "On app exit"

1. Login to Lockbox
2. Start typing in the search/filter field.
3. Background Lockbox
4. Foreground Lockbox

Result: 
- The login screen flickers.
- Search field is unresponsive
- After a while in this state the device starts to overheat.

Here is a video link: 
- https://www.youtube.com/watch?v=SjBQWdcVkr8&pbjreload=10

Depends on #351

**Comment by devinreams** [comment] 2018-05-17 15:30
Whoaaaa that's neat. Thanks @SimonBasca.

This looks like it may be similar to the "infinite scroll" or "cascading waterfall" or whatever behavior @changecourse also saw when he was doing some testing and filtering.

We _believe_ the behavior he saw was related to the filter/cancel button (and table) interactions so we should re-test this after #368. That _may_ fix this issue...

**Comment by devinreams** [comment] 2018-05-18 17:44
I just attempted/tested this again using iPhone 7 (Simulator, iOS 11.3) at commit 1abcbe7ebcc1e43e905e44f94ef6f841a0bdf2f2 (aka buddybuild 1165).

1. enabled Touch ID on device and installed Lockbox
2. tapped "Get Started" and signed in to FxA using `dreams+appletest@mozilla.com`
3. tapped "Settings" and changed to lock "on app exit"
3. Once sync complete/items loaded, typed "faketester4" in search/filter
  - Result: 10+ filtered results
4. Tapped Home to background Lockbox
5. Tapped Lockbox to re-open/foreground Lockbox, authenticated with Touch ID

Previous Result: screen flickers, search field unresponsive

Current Result: search/filter field is cleared (no 'faketester4'), all items are shown, and no flickering or unexpected scrolling behavior.

@SimonBasca I'll close this as fixed as a) the behavior you saw shouldn't occur anymore with recent fixes to the filtering code and b) there's currently no expectation the search/filter should persist when backgrounding — so this is working as expected.

If you're able to reproduce the issue again please let us know how. Thanks for your help!

**Closed by devinreams** 2018-05-18 17:44 UTC
Labels: bug
