### ISSUE TITLE
Dead link to tutorial on editing entries

### ISSUE THREAD

**Issue by teonbrooks** [mozilla-lockbox/lockbox-ios#431] opened 2018-05-23 22:04 UTC
The link `Learn how to edit this entry >` at the bottom of a given password entry doesn't work

**Comment by devinreams** [comment] 2018-05-23 23:12
Duplicate of #172

**Comment by devinreams** [comment] 2018-05-23 23:13
Thanks @teonbrooks, we’ll have all those links hooked up shortly. We’re finishing up the final touches right now! 🎨

**Closed by devinreams** 2018-05-23 23:12 UTC
Labels: closed-duplicate
