### ISSUE TITLE
The app won't start after turning on the passcode in iOS settings

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#451] opened 2018-05-29 10:27 UTC
v1.0 (1343)
iPhone 8 Plus (11.3.1)

1. Make sure that Passcode is turned off in iOS settings.
2. Install Lockbox.
3. Log in with a valid account.
4. Force close the app.
5. Go to iOS settings and turn on the passcode.
6. Try to launch Lockbox.

Expected: The app launches successfully.

Actual: A black screen is displayed and the app doesn't launch.

**Comment by isabelrios** [comment] 2018-05-29 11:55
I have seen the same black screen but following different steps:
1-Log in with valid account
2-Going to Settings -> Autolock settings (change or not the selected option)
3-Close the app
4-Open it again

The app does not start, it shows the black screen
Commenting here since it looks like the same root cause but if you want me to open a separate issue, let me know!

**Comment by devinreams** [comment] 2018-05-29 18:38
@mozilla-lockbox/ux @csuciu @isabelrios can you all please help re-test that #451 is fixed using your test devices and the branch over at #452?

**Comment by isabelrios** [comment] 2018-05-29 20:15
So far I'm unable to reproduce following the steps as I did before. I will give it another try and comment here if it happens again. Thanks!

**Comment by devinreams** [comment] 2018-05-29 21:54
>So far I'm unable to reproduce following the steps as I did before. I will give it another try and comment here if it happens again. Thanks!

OK! Thank you 🙇 

We will get it merged onto `master` ASAP for future testing...

**Closed** 2018-05-29 23:07 UTC
Labels: MVP, P1, bug, in progress
